"""Independent compatibility regression for the failed offset fixtures."""
import importlib.util
from pathlib import Path
import unittest

spec = importlib.util.spec_from_file_location('boundary_audit',
    Path(__file__).parents[1]/'scripts/audit-m2a-boundary-flux.py')
audit = importlib.util.module_from_spec(spec)
spec.loader.exec_module(audit)


class BoundaryCompatibility(unittest.TestCase):
    def test_observed_offset_plateaus(self):
        # Independent recorded CFD values, not generated by the oracle.
        observed = {36: 1.2441040403653051e-6,
                    48: 6.9959295910943403e-7,
                    64: 3.9345240547556067e-7}
        for n, value in observed.items():
            result = audit.fixture(n, .25, 'fixed')
            predicted = result['reference_cell_divergence_estimate_per_s']
            self.assertLess(abs(predicted/value-1), 1e-6)

    def test_symmetry_and_higher_order_integration(self):
        for n in (36, 48, 64):
            self.assertLess(audit.fixture(n, 0., 'fixed')[
                'reference_cell_divergence_estimate_per_s'], 1e-9)
            result = audit.fixture(n, .25, 'fixed', gauss=True)
            self.assertLess(result['reference_cell_divergence_estimate_per_s'], 1e-9)
            self.assertLess(result['normal_correction_m_s'],1e-10)
            self.assertLess(abs(result['projected_net_flux_m3_s']),1e-18)
        # Rotational field has a different flux compatibility behaviour.
        self.assertLess(audit.fixture(36, .25, 'rotate')[
            'reference_cell_divergence_estimate_per_s'], 1e-9)


if __name__ == '__main__':
    unittest.main()
